rango/urls.py
from django.conf.urls import url

from . import views

app_name = 'rango'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_slug_name>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^goto/(?P<page_id>[\d]+)/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^search/$', views.search, name='search'),
]

"""
url(r'^register/$', views.register, name='register'),
url(r'^login/$', views.user_login, name='login'),
url(r'^logout/$', views.user_logout, name='logout'),
"""

tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse

from rango import views as rango_views, urls as rango_urls
from registration.backends.simple.views import RegistrationView


# Create a new class that redirects the user to the index page,
# if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, **kwargs):
        return reverse('register_profile')


urlpatterns = [url(r'^$', rango_views.index, name='index'),
               url(r'^rango/', include(rango_urls)),
               url(r'^admin/', admin.site.urls),
               url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
               url(r'^accounts/', include('registration.backends.simple.urls')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

from .constants import cat_name_max_length, page_title_max_length, integer_default_views_and_likes, url_max_length


class UserProfile(models.Model):
    # custom user profile class
    # linked to django.contrib.auth.models.User
    user = models.OneToOneField(User)

    # additional attributes
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

    def get_username(self):
        return self.user.username

    def get_email(self):
        return self.user.email

    def get_lname(self):
        return self.user.last_name

    def get_fname(self):
        return self.user.first_name


class Category(models.Model):
    name = models.CharField(max_length=cat_name_max_length, unique=True)
    views = models.IntegerField(default=integer_default_views_and_likes)
    likes = models.IntegerField(default=integer_default_views_and_likes)
    slug = models.SlugField(unique=True, default=uuid.uuid1())  # prettify urls avoiding spaces

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

    def pages_count(self):
        return self.page_set.count()

    pages_count.admin_order_field = 'page'


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=page_title_max_length)
    url = models.URLField(max_length=url_max_length)
    views = models.IntegerField(default=integer_default_views_and_likes)

    def __str__(self):
        return self.title

rango/forms.py
from django.contrib.auth.models import User
from django.forms import models
from django import forms

from rango.models import Category, Page, UserProfile

from .constants import cat_name_max_length, page_title_max_length, integer_default_views_and_likes, url_max_length


class UserForm(models.ModelForm):
    # attributes
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(models.ModelForm):
    # attributes
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user', )


class CategoryForm(models.ModelForm):
    name = forms.CharField(max_length=cat_name_max_length,
                           help_text="Please enter the Category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=integer_default_views_and_likes)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=integer_default_views_and_likes)
    slug = forms.CharField(widget=forms.HiddenInput, required=False)

    # an inline class to define additional information on the form
    class Meta:
        model = Category
        fields = ('name',)


class PageForm(models.ModelForm):
    title = forms.CharField(max_length=page_title_max_length,
                            help_text="Please enter the Page title")
    url = forms.URLField(max_length=url_max_length,
                         help_text="Please enter the url of the Page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=integer_default_views_and_likes)

    # an inline class to define additional information on the form
    class Meta:
        model = Page
        exclude = ('category', )

    # override clean method called right before save
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

rango/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from rango.forms import CategoryForm, PageForm, UserProfileForm
from rango.webhose_search import run_query
from .constants import integer_default_views_and_likes
from .models import Category, Page, UserProfile


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')

    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie

    # Update/set the visits cookie
    request.session['visits'] = visits


def index(request):
    # test cookies
    request.session.set_test_cookie()
    # get top 5 categories
    top_categories = Category.objects.order_by('-likes')[:5]
    top_pages = Page.objects.order_by('-views')[:5]
    visitor_cookie_handler(request)
    # dictionary to pass to the template
    context_dict = {'boldmessage': 'Hello from Rango !',
                    'top_categories': top_categories,
                    'top_pages': top_pages,
                    'visits': request.session['visits']}

    # get response early to set cookies
    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    # test cookies
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    # dictionary to pass to the template
    context_dict = {'boldmessage': 'Hello from About Rango !'}

    visitor_cookie_handler(request)
    count = request.session.get('visits', 0)
    context_dict['visit_count'] = count

    # return a rendered response to the client
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = dict()

    category = get_object_or_404(Category, slug=category_name_slug)
    context_dict['category'] = category

    pages = Page.objects.filter(category=category).order_by('-views')
    context_dict['pages'] = pages

    context_dict['query'] = category.name

    if request.method == 'POST':

        query = request.POST['query'].strip()

        if query:
            # Run our search API function to get the results list!
            result_list = run_query(query)
            context_dict['query'] = query
            context_dict['result_list'] = result_list

    # GET
    return render(request, 'rango/category.html', context_dict)


def get_category_list(max_results=0, starts_with=''):
    if len(starts_with):
        cat_list = Category.objects.filter(name__istartswith=starts_with)
    else:
        cat_list = Category.objects.all()
    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)
    return render(request, 'rango/cats.html', {'cats': cat_list})


def search(request):
    result_list = []
    query = None
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            # Run our Webhose search function to get the results list!
            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list, 'query': query})


def track_url(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    page.views += 1
    page.save()
    return redirect(page.url)


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect('rango:index')

        print(form.errors)

    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm(
        {'website': userprofile.website, 'picture': userprofile.picture}
    )
    if request.method == 'POST' and user == request.user:
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

    return render(request, 'rango/profile.html', {
        'userprofile': userprofile,
        'selecteduser': user,
        'form': form
    })


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html',
                  {'userprofile_list': userprofile_list}
                  )


@login_required
def like_category(request):
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
        return HttpResponse(likes)


"""
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rango/unused_register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def user_login(request):
    errors = None
    if request.method == 'POST':
        # POST
        # as opposed to request.POST['username']
        # request.POST.get() will return None if there is an error
        username = request.POST.get('username')
        password = request.POST.get('password')
        # verify authentication with Django provided authentication system
        # returns a User if anything OK
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            return HttpResponse('Your Rango account is disabled !')
        print("Invalid login details: {0}, {1}".format(username, password))
        if not errors:
            errors = dict()
        errors['invalid login'] = "Invalid login details"
    # GET
    return render(request, 'rango/unused_login.html', {'errors': errors})
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))

"""


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return index(request)

        print(form.errors)

    return render(request, 'rango/add_category.html', context={'form': form, })


@login_required
def add_page(request, category_slug_name):
    category = get_object_or_404(Category, slug=category_slug_name)

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            page = form.save(commit=False)

            page.category = category
            page.views = integer_default_views_and_likes
            page.save()
            return redirect('rango:show_category', category.slug)

        print(form.errors)

    context_dict = {'form': form, 'category': category, 'query': None}
    return render(request, 'rango/add_page.html', context=context_dict)

templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title %}Add a Category{% endblock %}

{% block content %}
    <form id="category_form" action="{% url 'rango:add_category' %}" method="post">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}
        <div class="col-xs-12">
            {{ visible_field.errors }}
        </div>
        <div class="col-xs-12">
            {% for visible_field in form.visible_fields %}
                <p>{{ visible_field.help_text }}</p>
                <p>{{ visible_field }}</p>
            {% endfor %}
        </div>
        <div class="col-xs-12">
            <input class="btn btn-default" type="submit" name="submit" value="Create Category" />
        </div>
    </form>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">

<head>
    <title>Rango</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <!-- JavaScript -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/rango_jquery.js' %}"></script>
    <script src="{% static 'js/rango_ajax.js' %}"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="container">
            <h1>{% block title %}Page Title{% endblock %}</h1>
        </div>
        <hr/>
        <div class="container">
            <div class="col-xs-3">
                <h5>Navigate</h5>
                <ul class="list-unstyled">
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'auth_login' %}">Login</a><li>
                        <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                    {% else %}
                        {% block links %}{% endblock %}
                        <li><a href="{% url 'rango:add_category' %}">New Category</a></li>
                        <li><a href="{% url 'auth_password_change' %}">Change password</a></li>
                        <li><a href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <a href="{% url 'rango:list_profiles' %}">List Profiles</a>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a><li>
                    {% endif %}
                    <li><a href="{% url 'rango:search' %}">Search</a></li>
                    <li><a href="{% url 'rango:index' %}">Home</a></li>
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                </ul>
                <hr/>
                <h5>Categories</h5>
                <ul class="nav nav-list flex-column list-unstyled">
                    <li class="nav-item">Type to find a category</li>
                    <form>
                    <li class="nav-item"><input class="search-query form-control" type="text"
                    name="suggestion" value='' id="suggestion"  title="suggestion" />
                    </li>
                    </form>
                </ul>
                <hr>
                <ul class="list-unstyled" id="cats">
                </ul>
                {% comment %}<ul class="list-unstyled">
                    {% get_category_list category %}
                </ul>{% endcomment %}
            </div>
             <div class="col-xs-9">
                {% block content %}{% endblock %}
             </div>
        </div>
        <hr/>
        <div class="container">
            <p>&copy; Tango with Django followed by Adrian Pothuaud</p>
        </div>
    </div>
</body>

</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,
        initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
        <title>
        Rango
        </title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
        <!-- Custom styles for this template -->
        <link href=
        "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
        rel="stylesheet">
    </head>

<body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
                aria-controls="navbar"
        aria-expanded="false"
        aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rango:index' %}">
                    Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:about' %}">
                    About
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rango:add_cateory' %}">
                        Add a New Category
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                        Logout
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registration_register' %}">
                        Register Here
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_login' %}">
                        Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <h5>Navigate</h5>
                <ul class="list-unstyled">
                    {% block links %}{% endblock %}
                    {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'auth_login' %}">Login</a><li>
                        <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                    {% else %}
                        <li><a href="{% url 'rango:add_category' %}">New Category</a></li>
                        <li><a href="{% url 'auth_password_change' %}">Change password</a></li>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a><li>
                    {% endif %}
                </ul>
                <hr/>
                <h5>Categories</h5>
                <ul class="list-unstyled">
                    {% get_category_list category %}
                </ul>
            </div>
            <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
                {% block content %}{% endblock %}
            </div>
        </div>
        <hr/>
        <div class="container">
            <p>&copy; Tango with Django</p>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}
    {% if category %}
        {{ category.name }} <small>category</small>
    {% else %}
        Category does not exist
    {% endif %}
{% endblock %}

{% block links %}
    {% if user.is_authenticated %}
        <li><a href="{% url 'rango:add_page' category_slug_name=category.slug %}">Add a Page</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{category.id}}"
                class="btn btn-primary btn-sm" type="button">
                Like
                </button>
            {% endif %}
        </div>
        {% if pages %}
            <h3>Pages <small>from {{ category.name }}</small></h3>
            <div class="col-xs-12"></div>
            <ul class="list-unstyled">
                {% for page in pages %}
                    <li>
                        <a href="{% url 'rango:goto' page.id %}">{{ page.title }}</a>
                        ({{ page.views }} view{{ page.views|pluralize:',s' }})
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <h3>Search for another page</h3>
            <form class="form-inline" id="search_form" method="post" action="{% url 'rango:show_category' category.slug %}">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" size="50"  title="Query" name="query" id="query"
                    {% if query %}
                        value="{{ query }}"
                    {% endif %}
                    >
                </div>
                <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
            </form>

            <div>
                {% if result_list %}
                    <h3>Results</h3>
                    <div class="list-group">
                        {% for result in result_list %}
                            {% if result.title %}
                                <div class="list-group-item">
                                    <h4 class="list-group-item-heading">
                                        <a href="{{ result.url }}">{{ result.title }}</a>
                                    </h4>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endif %}
    {% else %}
        The specified category does not exist !
    {% endif %}
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Register for Rango{% endblock %}

{% block links %}
    <li><a href="{% url 'rango:index' %}">Home</a></li>
    <li><a href="{% url 'rango:about' %}">About Rango</a></li>
{% endblock %}

{% block content %}
    {% if registered %}
        <p>Rango says : <strong>thank you for registering !</strong></p>
        <p>Return to the <a href="{% url 'rango:index' %}">home page</a></p>
    {% else %}
        <p>Rango says : <strong>register here !</strong></p>
        <form class="form-group" id="user_form" action="{% url 'rango:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-xs-12">
                {% for visible_field in user_form.visible_fields %}
                    <p>{{ visible_field.label }}</p>
                    <p>{{ visible_field.help_text }}</p>
                    <p>{{ visible_field }}</p>
                    <p>{{ visible_field.errors }}</p>
                {% endfor %}
                {% for visible_field in profile_form.visible_fields %}
                    <p>{{ visible_field.label }}</p>
                    <p>{{ visible_field.help_text }}</p>
                    <p>{{ visible_field }}</p>
                    <p>{{ visible_field.errors }}</p>
                {% endfor %}
            </div>
            <div class="col-xs-12 text-center">
                <input class="btn btn-default" type="submit" name="submit" value="Register" />
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/rango/unused_login.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Login to Rango{% endblock %}

{% block links %}
    <li><a href="{% url 'rango:index' %}">Home</a></li>
    <li><a href="{% url 'rango:about' %}">About Rango</a></li>
{% endblock %}

{% block content %}
    {% if errors %}
        <div>
            {% for error in errors %}
                <div class="panel panel-danger">
                    <div class="panel-body">{{ error }}</div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <form class="form-group" id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        <label id="username_label">Username: </label>
        <br/>
        <input class="form-control" aria-labelledby="username_label" type="text" name="username" value="" size="50"  title="Username"/>
        <br />
        <label>Password: </label><br/>
        <input class="form-control" aria-labelledby="password_label"  type="password" name="password" value="" size="50" title="password" />
        <br />
        <input class="btn btn-default" type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/unused_register.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Register for Rango{% endblock %}

{% block links %}
    <li><a href="{% url 'rango:index' %}">Home</a></li>
    <li><a href="{% url 'rango:about' %}">About Rango</a></li>
{% endblock %}

{% block content %}
    {% if registered %}
        <p>Rango says : <strong>thank you for registering !</strong></p>
        <p>Return to the <a href="{% url 'rango:index' %}">home page</a></p>
    {% else %}
        <p>Rango says : <strong>register here !</strong></p>
        <form class="form-group" id="user_form" action="{% url 'rango:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-xs-12">
                {% for visible_field in user_form.visible_fields %}
                    <p>{{ visible_field.label }}</p>
                    <p>{{ visible_field.help_text }}</p>
                    <p>{{ visible_field }}</p>
                    <p>{{ visible_field.errors }}</p>
                {% endfor %}
                {% for visible_field in profile_form.visible_fields %}
                    <p>{{ visible_field.label }}</p>
                    <p>{{ visible_field.help_text }}</p>
                    <p>{{ visible_field }}</p>
                    <p>{{ visible_field.errors }}</p>
                {% endfor %}
            </div>
            <div class="col-xs-12 text-center">
                <input class="btn btn-default" type="submit" name="submit" value="Register" />
            </div>
        </form>
    {% endif %}
{% endblock %}